# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-08 23:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 3, 9, 2, 30, 51, 205887), verbose_name='Опубликована'),
        ),
    ]
