# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-10 09:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20180309_0231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 3, 10, 12, 10, 0, 894399), verbose_name='Опубликована'),
        ),
    ]
