# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 09:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20180325_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 3, 25, 12, 29, 46, 453665), verbose_name='Опубликована'),
        ),
    ]
