# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-25 11:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20180325_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='posted',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2018, 3, 25, 14, 10, 46, 621905), verbose_name='Опубликована'),
        ),
    ]
