# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-30 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choise',
            new_name='Chose',
        ),
        migrations.RenameField(
            model_name='chose',
            old_name='choise_text',
            new_name='chose_text',
        ),
    ]
